# Generated by Django 4.2 on 2025-05-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-created_at'], 'verbose_name': 'Источник новостей', 'verbose_name_plural': 'Источники новостей'},
        ),
        migrations.AddField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Отображать ли статью пользователям', verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Отображать в рекомендуемых статьях', verbose_name='Рекомендуемая'),
        ),
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.TextField(blank=True, help_text='Краткое содержание статьи (автоматически или из источника)', verbose_name='Краткое содержание'),
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='source',
            name='articles_count',
            field=models.PositiveIntegerField(default=0, help_text='Общее количество статей с этого источника', verbose_name='Количество статей'),
        ),
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание источника', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='source',
            name='last_parsed',
            field=models.DateTimeField(blank=True, help_text='Когда последний раз парсился источник', null=True, verbose_name='Последний парсинг'),
        ),
        migrations.AddField(
            model_name='source',
            name='update_frequency',
            field=models.PositiveIntegerField(default=60, help_text='Как часто парсить источник в минутах', verbose_name='Частота обновления (мин)'),
        ),
        migrations.AddField(
            model_name='source',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, help_text='Полный текст статьи', verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(help_text='Когда статья была опубликована', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='core.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Заголовок статьи', max_length=500, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tone',
            field=models.CharField(choices=[('positive', 'Позитивная'), ('neutral', 'Нейтральная'), ('negative', 'Негативная')], default='neutral', help_text='Эмоциональная тональность статьи', max_length=10, verbose_name='Тональность'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(choices=[('politics', 'Политика'), ('business', 'Бизнес'), ('technology', 'Технологии'), ('sports', 'Спорт'), ('entertainment', 'Развлечения'), ('science', 'Наука'), ('health', 'Здоровье'), ('world', 'Мир'), ('society', 'Общество'), ('culture', 'Культура'), ('other', 'Другое')], default='other', help_text='Основная тема статьи', max_length=20, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(help_text='Оригинальная ссылка на статью', unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='source',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Включен ли парсинг этого источника', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(help_text='Название источника новостей', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('rss', 'RSS'), ('html', 'HTML'), ('spa', 'SPA (JavaScript)'), ('api', 'API'), ('tg', 'Telegram')], help_text='Способ парсинга источника', max_length=10, verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.URLField(help_text='Ссылка на источник', unique=True, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='core_articl_publish_a6a48c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['topic'], name='core_articl_topic_465d88_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tone'], name='core_articl_tone_7797d7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source'], name='core_articl_source__2294d3_idx'),
        ),
    ]
