# Generated by Django 4.2 on 2025-05-25 03:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_article_options_alter_source_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='core_articl_tone_7797d7_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tone',
        ),
        migrations.AddField(
            model_name='article',
            name='is_analyzed',
            field=models.BooleanField(default=False, help_text='Был ли проведен автоматический анализ текста', verbose_name='Проанализирована'),
        ),
        migrations.AddField(
            model_name='article',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Географические упоминания (определяются автоматически)', size=None, verbose_name='Локации'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Ключевые слова и фразы (определяются автоматически)', size=None, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(choices=[('politics', 'Политика'), ('economics', 'Экономика'), ('technology', 'Технологии'), ('science', 'Наука'), ('sports', 'Спорт'), ('culture', 'Культура'), ('health', 'Здоровье'), ('education', 'Образование'), ('environment', 'Экология'), ('society', 'Общество'), ('war', 'Война и конфликты'), ('international', 'Международные отношения'), ('business', 'Бизнес'), ('finance', 'Финансы'), ('entertainment', 'Развлечения'), ('travel', 'Путешествия'), ('food', 'Еда'), ('fashion', 'Мода'), ('auto', 'Автомобили'), ('real_estate', 'Недвижимость'), ('other', 'Прочее')], default='other', help_text='Основная тема статьи (определяется автоматически)', max_length=20, verbose_name='Тема'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_analyzed'], name='core_articl_is_anal_44e720_idx'),
        ),
    ]
