# Generated by Django 4.2 on 2025-05-28 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_api_requests_per_day',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_custom_sources',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='max_saved_articles',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='api_calls_limit',
            field=models.PositiveIntegerField(blank=True, help_text='null = безлимит', null=True, verbose_name='Лимит API вызовов в день'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='daily_articles_limit',
            field=models.PositiveIntegerField(blank=True, help_text='null = безлимит', null=True, verbose_name='Лимит статей в день'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='exports_limit',
            field=models.PositiveIntegerField(blank=True, help_text='null = безлимит', null=True, verbose_name='Лимит экспортов в месяц'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='favorites_limit',
            field=models.PositiveIntegerField(blank=True, help_text='null = безлимит', null=True, verbose_name='Лимит избранных статей'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list, help_text='Массив строк с описанием возможностей плана', verbose_name='Список функций'),
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_articles_read', models.PositiveIntegerField(default=0, verbose_name='Статей прочитано сегодня')),
                ('daily_api_calls', models.PositiveIntegerField(default=0, verbose_name='API вызовов сегодня')),
                ('monthly_exports', models.PositiveIntegerField(default=0, verbose_name='Экспортов в этом месяце')),
                ('total_favorites', models.PositiveIntegerField(default=0, verbose_name='Всего избранных статей')),
                ('last_daily_reset', models.DateField(auto_now_add=True, verbose_name='Последний сброс дневных лимитов')),
                ('last_monthly_reset', models.DateField(auto_now_add=True, verbose_name='Последний сброс месячных лимитов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отслеживание использования',
                'verbose_name_plural': 'Отслеживание использования',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('card', 'Банковская карта'), ('bank_transfer', 'Банковский перевод'), ('crypto', 'Криптовалюта'), ('mobile', 'Мобильные платежи')], max_length=20, verbose_name='Тип платежа')),
                ('last_four', models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='Бренд карты')),
                ('expires_month', models.PositiveIntegerField(blank=True, null=True, verbose_name='Месяц истечения')),
                ('expires_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год истечения')),
                ('provider_id', models.CharField(max_length=100, verbose_name='ID у провайдера платежей')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Способ оплаты',
                'verbose_name_plural': 'Способы оплаты',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='BYN', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('succeeded', 'Успешно'), ('failed', 'Неудачно'), ('cancelled', 'Отменен'), ('refunded', 'Возвращен')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_intent_id', models.CharField(max_length=100, unique=True, verbose_name='ID платежного намерения')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID транзакции')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Причина неудачи')),
                ('provider_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ провайдера')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paymentmethod', verbose_name='Способ оплаты')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.usersubscription', verbose_name='Подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_history', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История платежей',
                'verbose_name_plural': 'История платежей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['user', 'status'], name='accounts_pa_user_id_ea1b56_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['payment_intent_id'], name='accounts_pa_payment_4b15b2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenthistory',
            index=models.Index(fields=['created_at'], name='accounts_pa_created_1db8d2_idx'),
        ),
    ]
